name: Deploy Python project to Azure Function App

on:
    push:
        branches: ["test"]

env:
    AZURE_FUNCTIONAPP_NAME: "test-app"
    AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
    PYTHON_VERSION: "3.9"

jobs:
    build:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: "Checkout GitHub Action"
              uses: actions/checkout@v3

            - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ env.PYTHON_VERSION }}

            - name: "Setup SSH Keys"
              uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: |
                      ${{ secrets.PRIVATE_REPO1_SSH }}
                      ${{ secrets.PRIVATE_REPO2_SSH }}
            - name: "Resolve Project Dependencies Using Pip"
              shell: bash
              run: |
                  pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt --target=".python_packages/lib/site-packages"
                  popd
            - name: Zip artifact for deployment
              run: zip release.zip ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} -r
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                  name: python-app
                  path: |
                      release.zip
                      !venv/
    Deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: dev

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                  name: python-app
                  path: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
            - name: unzip artifact for deployment
              run: |
                  pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
                  unzip release.zip
                  rm release.zip
                  popd

            - name: "Run Azure Functions Action"
              uses: Azure/functions-action@v1
              id: fa
              with:
                  app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
                  package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
                  publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
                  # scm-do-build-during-deployment: true
                  # enable-oryx-build: true
